- uses: actions/checkout@v3

- name: generate-snake-game-from-github-contribution-grid
  id: generate_snake
  uses: Platane/snk@v3.3.0
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    github_user_name: starewxz
    outputs: github-snake.svg

- name: Show generated files
  run: find . -type f

- name: Commit and push snake SVG
  run: |
    if [ -f github-snake.svg ]; then
      git config --local user.name "github-actions[bot]"
      git config --local user.email "github-actions[bot]@users.noreply.github.com"
      git add github-snake.svg
      git commit -m "Update snake SVG" || echo "No changes to commit"
      git push
    else
      echo "github-snake.svg not found, skipping commit"
    fi